swagger: '2.0'
info:
  title: Transaction Management API
  description: API for managing transactions in the application
  version: "1.0.0"
host: localhost:3001
basePath: '/api/v1'
schemes:
  - https
  - http
paths:
  /account/{accountId}/transactions:
    get:
      summary: Retrieve transactions for a specified account
      description: Fetches all transactions for a specified account. Optionally, transactions can be filtered by a specified month if the month parameter is provided.
      parameters:
        - in: path
          name: accountId
          required: true
          description: The unique identifier of the account
          type: integer
        - in: query
          name: month
          required: false
          default: 0
          description: The month offset (0 for current month, 1 for last month, etc.)
          type: integer
      responses:
        200:
          description: A list of transactions for the specified account or month
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        404:
          description: No transactions found for the specified account or month

  /transaction/{transactionId}:
    get:
      summary: Get details of a specific transaction
      description: Fetches details of a specified transaction.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Details of the transaction
          schema:
            $ref: '#/definitions/Transaction'
        404:
          description: Transaction not found
  
  /transaction/{transactionId}/update:
    patch:
      summary: Partially update a transaction's category or notes
      description: Updates specific fields (category or notes) of an existing transaction.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
        - in: body
          name: transactionUpdate
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
                format: text
                description: The new category of the transaction.
              notes:
                type: string
                format: text
                description: The new notes of the transaction.
      responses:
        200:
          description: Transaction partially updated
        400:
          description: Invalid input
        404:
          description: Transaction not found

definitions:
