swagger: '2.0'
info:
  title: Transaction Management API
  description: API for managing transactions in the application
  version: "1.0.0"
host: localhost:3001
basePath: '/api/v1'
schemes:
  - https
  - http
paths:
  /transactions:
    get:
      summary: Retrieve transactions for the current month
      description: Fetches all transactions grouped by account for the current month.
      responses:
        200:
          description: A list of transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        404:
          description: No transactions found

  /transactions/{transactionId}:
    get:
      summary: Get details of a specific transaction
      description: Fetches details of a specified transaction.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Details of the transaction
          schema:
            $ref: '#/definitions/Transaction'
        404:
          description: Transaction not found
    post:
      summary: Create a new transaction
      description: Adds a new transaction to the system.
      parameters:
        - in: body
          name: transaction
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        201:
          description: Transaction created
        400:
          description: Invalid input

    put:
      summary: Update a transaction
      description: Updates an existing transaction.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
        - in: body
          name: transaction
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        200:
          description: Transaction updated
        404:
          description: Transaction not found

    delete:
      summary: Delete a transaction
      description: Delete a specified transaction.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Transaction deleted
        404:
          description: Transaction not found

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
      account:
        type: string
      amount:
        type: number
      date:
        type: string
      description:
        type: string
